---
version: "3.9"

services:

  app:
    image: "ghcr.io/roib20/petinvent:latest"
    container_name: "petinvent_app"
    hostname: "app"
    restart: "unless-stopped"
    environment:
        - "POSTGRES_DB=${POSTGRES_DB:?err}"
        - "POSTGRES_USER=${POSTGRES_USER:?err}"
        - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}"
        - "DB_HOSTNAME=${DB_HOSTNAME:-db}"
        - "POSTGRES_PORT=${POSTGRES_PORT:-5432}"
        - "SECRET_KEY=${SECRET_KEY}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - "database_network"
    ports:
      - "${WSGI_PORT:-5000}:5000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 5s
      timeout: 10s
      retries: 20

  db:
    hostname: "${DB_HOSTNAME:?err}"
    container_name: "petinvent_db"
    image: "rapidfort/postgresql:${RAPIDFORT_POSTGRESQL_TAG:-15.3}"
    volumes:
        - "petinvent_db_data:/bitnami/postgresql"
    networks:
      - "database_network"
    restart: "unless-stopped"
    environment:
        - "POSTGRESQL_DATABASE=${POSTGRES_DB:?err}"
        - "POSTGRESQL_USERNAME=${POSTGRES_USER:?err}"
        - "POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD:?err}"
        - "TZ=${TZ:-Etc/UTC}"
        - "PGTZ=${TZ:-Etc/UTC}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=$${POSTGRESQL_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  database_network:
    driver: bridge
    external: false
    name: database_network

volumes:
  petinvent_db_data:
    external: false
    name: petinvent_db_data
