apiVersion: v1
kind: Service
metadata:
  name: {{ include "petbuddy.fullname" . }}
  labels:
    {{- include "petbuddy.labels" . | nindent 4 }}
spec:
  type: {{ if .Values.ingress.enabled }}ClusterIP{{ else }}{{ .Values.service.type }}{{ end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "petbuddy.selectorLabels" . | nindent 4 }}
